Task1ASP/Areas/Admin/Controllers/AdminArticleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using BlogAsp.BLL.Interfaces;
using BlogAsp.Models.Models;
using Task1ASP.Areas.Admin.Models;
using Task1ASP.Models.Article;

namespace Task1ASP.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminArticleController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IArticleService _articleService;
        private readonly ITagService _tagService;

        public AdminArticleController(IMapper mapper, IArticleService articleService, ITagService tagService)
        {
            _mapper = mapper;
            _articleService = articleService;
            _tagService = tagService;
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ArticleVm articleVm)
        {
            _articleService.Create(_mapper.Map<Article>(articleVm));

            return RedirectToAction("GetArticles", "Article", new { area = "" });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var tags = _tagService.GetAll();
            var checkTags = _mapper.Map<ICollection<CheckModel>>(tags);

            var article = _articleService.Get(id);
            var editArticle = _mapper.Map<EditArticle>(article);

            foreach (var item in checkTags)
            {
                if (editArticle.Tags.Any(tag => tag.Text == item.Tag?.Text))
                {
                    item.Checked = true;
                }
            }

            editArticle.CheckTags = checkTags;

            return View(editArticle);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditArticle editArticle, string[] names)
        {
            if (!ModelState.IsValid)
            {
                return View(editArticle);
            }

            var article = _articleService.Get(editArticle.Id);

            _mapper.Map(editArticle, article);

            if (names != null)
            {
                article.Tags.Clear();
                _articleService.GetArticlesWithTags(article, names);
            }
            else
            {

                article.Tags = _articleService.GetTags(article.Id).ToList();
            }

            _articleService.Update(article);

            return RedirectToAction("GetArticles", "Article", new { area = "" });
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(_articleService.Get(id));
        }

        [HttpPost]
        public ActionResult Delete(Article article)
        {
            _articleService.Delete(article.Id);

            return RedirectToAction("GetArticles", "Article", new { area = "" });
        }

        [HttpGet]
        public ActionResult AddTag(int id)
        {
            var article = _articleService.Get(id);
            var articleAddTag = _mapper.Map<ArticleAddTagVm>(article);

            articleAddTag.PopularTags = _articleService.GetMostPopularTags(article, 5).ToList();

            return View("AddTagDetails", articleAddTag);
        }

        [HttpPost]
        public ActionResult AddTag(ArticleAddTagVm articleAddTag)
        {
            var article = _articleService.Get(articleAddTag.Id);

            foreach (var item in articleAddTag.PopularTags)
            {
                if (article.Tags.All(tag => tag.Text != item))
                {
                    article.Tags.Add(new Tag { Text = item });
                }
            }

            _articleService.Update(article);

            return RedirectToAction("GetArticles", "Article", new { area = "" });
        }
    }
}

Task1ASP/Areas/Admin/Views/AdminArticle/AddTag.cshtml
@model List<string>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddTag", "AdminArticle", FormMethod.Post))
{
    @Html.ListBox("selectedTags", new MultiSelectList(Model), new { htmlAttributes = new { @class = "mdb-select colorful-select dropdown-primary" } })
    <input type="submit" value="Apply" class=" btn btn-primary btn-sm" />

}

Task1ASP/Areas/Admin/Views/AdminArticle/AddTagDetails.cshtml
@model Task1ASP.Areas.Admin.Models.ArticleAddTagVm
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.Title = "AddTagDetails";
}
@using (Html.BeginForm("AddTag", "AdminArticle", FormMethod.Post))
{
	<div>
		@Html.HiddenFor(model => model.Id)
		<dl class="dl-horizontal font-details">
			<dt>
				@Html.DisplayNameFor(model => model.Name)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Name)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Date)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Date)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Text)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Text, new { htmlAttributes = new { @class = "animals" } })
			</dd>
			<dt>Tags</dt>
			<dd>
				@foreach (var tag in Model.Tags)
				{
					@Html.ActionLink($"#{tag.Text}", "TagActive", new { area = "", controller = "Article", id = tag.Id })
				}
			</dd>
		</dl>
	</div>
	<div>@Html.DisplayName("Рекомендуемые теги:")</div>
	@Html.ListBoxFor(model => model.PopularTags, new MultiSelectList(Model.PopularTags, Model.Tags.FirstOrDefault()?.Text), new { htmlAttributes = new { @class = "mdb-select colorful-select dropdown-primary" } })
	<input type="submit" value="Apply" class=" btn btn-primary btn-sm" />
}

Task1ASP/Areas/Admin/Views/AdminArticle/AddTagsPartial.cshtml
@model ICollection<Task1ASP.Areas.Admin.Models.CheckModel>
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}
@foreach (var s in Model)
{
	<label class="checkbox checkbox-inline">
		@if (s.Checked)
		{
			<input type="checkbox" name="names" checked="checked" value="@s.Tag.Text">@s.Tag.Text
		}
		else
		{
			<input type="checkbox" name="names" value="@s.Tag.Text">@s.Tag.Text
		}
	</label>
}

Task1ASP/Areas/Admin/Views/AdminArticle/Create.cshtml
@model Task1ASP.Models.Article.ArticleVm
@{
	Layout = "~/Views/Shared/_Layout.cshtml";

}

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.Text, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Task1ASP/Areas/Admin/Views/AdminArticle/Delete.cshtml
@model BlogAsp.Models.Models.Article

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal font-details">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div>
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

Task1ASP/Areas/Admin/Views/AdminArticle/Edit.cshtml
@using Task1ASP.Areas.Admin.Models
@model EditArticle

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Id)
		<div class="form-group">
			@Html.LabelFor(model => model.Tags, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@{ Html.RenderPartial("AddTagsPartial", Model.CheckTags);}
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.Text, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control widthstatic" } })
				@Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-default" />
			</div>
		</div>
	</div>
}